version: '3'

services:
  web:
    build: .
    ports:
      - "8009:8009"
    env_file: .env
    volumes:
      - .:/var/www
    container_name: cardThing
    command: /usr/bin/supervisord --nodaemon