"""empty message

Revision ID: 7eb82d844e18
Revises: af24d684739f
Create Date: 2020-04-26 04:53:26.275019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7eb82d844e18'
down_revision = 'af24d684739f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('encryption_key', sa.String(length=12), nullable=True))
    op.drop_column('user', 'secret_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('secret_key', mysql.VARCHAR(length=12), nullable=True))
    op.drop_column('user', 'encryption_key')
    # ### end Alembic commands ###
