"""empty message

Revision ID: 9d4b7db02fd7
Revises: 9be6533cf9cd
Create Date: 2020-04-26 06:30:36.843397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d4b7db02fd7'
down_revision = '9be6533cf9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vault', sa.Column('uuid', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_vault_uuid'), 'vault', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vault_uuid'), table_name='vault')
    op.drop_column('vault', 'uuid')
    # ### end Alembic commands ###
