"""vault table

Revision ID: af24d684739f
Revises: f45efeef2038
Create Date: 2020-04-24 04:20:56.726743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af24d684739f'
down_revision = 'f45efeef2038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_four', sa.Integer(), nullable=True),
    sa.Column('card_token', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vault')
    # ### end Alembic commands ###
